function err=fit_chaps(x,ne,h,forc,tol,fac,f)
errextra=sinh(2*(x-forc)./tol);
x=exp(reshape(x,3,[]));
ne_ch=chapman(h,x);
err=(ne-ne_ch)./fac;
err=asinh(err/2);
%errextra=zeros(size(errextra));
err=[err;errextra];
if f, err=norm(err); end
