function [ BX,BY,BZ ] = BSPCAR( TETA,PHI,BR,BTET,BPHI )
%BSPCOR CALCULATES CARTESIAN FIELD COMPONENTS FROM SPHERICAL ONES
%
%      SUBROUTINE BSPCAR(TETA,PHI,BR,BTET,BPHI,BX,BY,BZ)
%  *********************************************************************
%   CALCULATES CARTESIAN FIELD COMPONENTS FROM SPHERICAL ONES
%-----INPUT:   TETA,PHI - SPHERICAL ANGLES OF THE POINT IN RADIANS
%              BR,BTET,BPHI -  SPHERICAL COMPONENTS OF THE FIELD
%-----OUTPUT:  BX,BY,BZ - CARTESIAN COMPONENTS OF THE FIELD
%  AUTHOR: NIKOLAI A. TSYGANENKO, INSTITUTE OF PHYSICS, ST.-PETERSBURG
%      STATE UNIVERSITY, STARY PETERGOF 198904, ST.-PETERSBURG, RUSSIA
%      (now the NASA Goddard Space Fligth Center, Greenbelt, Maryland)
%  *********************************************************************

%        IMPLICIT NONE
%
%        REAL TETA,PHI,BR,BTET,BPHI,BX,BY,BZ,S,C,SF,CF,BE

  S=sin(TETA);
  C=cos(TETA);
  SF=sin(PHI);
  CF=cos(PHI);
  BE=BR*S+BTET*C;
  BX=BE*CF-BPHI*SF;
  BY=BE*SF+BPHI*CF;
  BZ=BR*C-BTET*S;

end

