function [ RDNO ] = RDNO( H,HB,RDO2H,RDOH,RNO )
%RDNO NO+ RELATIVE PERCENTAGE DENSITY
%
%      REAL FUNCTION RDNO(H,HB,RDO2H,RDOH,RNO)      
% D.BILITZA, 1978. NO+ RELATIVE PERCENTAGE DENSITY ABOVE 100KM.                 
% FOR MORE INFORMATION SEE SUBROUTINE RDHHE.       
  if H <= HB
    RDNO=100.0-RDO2H-RDOH;
  else
    RDNO=RNO*RDO2H;
  end

end

